image: fedora:30

variables:
  DEPENDENCIES: xmlto docbook-utils libxslt make git discount
  LANG: en_US.UTF-8

pages:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    # Generate specs locally
    - cd web-export
    - LC_ALL=$LANG ./update.py
    - cd ..
    # That worked, clean up
    - git clean -dxf
    - rm -rf public/
    # Generate specs for older versions
    - cd web-export
    - sed -i 's/USELOCALFILES = True/USELOCALFILES = False/' update.py
    - LC_ALL=$LANG ./update.py
    - cd ..

  artifacts:
    paths:
    - public
